language: cpp
dist: trusty

sudo: required

services:
  - docker
  
before_install:
  - docker pull yadoms/build_for_ubuntu
  
script:
  - docker run -e YADOMS_BRANCH=${TRAVIS_BRANCH} yadoms/build_for_ubuntu